name: bitrise-test-check

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bitrise-test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install BitriseCLI
      - run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          curl -fL https://github.com/bitrise-io/bitrise/releases/download/1.47.0/bitrise-$(uname -s)-$(uname -m) > $GITHUB_WORKSPACE/bin/bitrise
          chmod +x $GITHUB_WORKSPACE/bin/bitrise

      - name: Test step
      - run: |
          bitrise run test
